server.port=8080
spring.config.import=optional:file:./application-local.properties
openweathermap.api-key=${OPENWEATHER_API_KEY:}
openweathermap.base-url=https://api.openweathermap.org/data/2.5/weather

cities.file=cities.json
cache.ttl-seconds=300

# Auth0 API. Fill real values in application-local.properties
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH0_ISSUER_URI:}
spring.security.oauth2.resourceserver.jwt.audiences=${AUTH0_AUDIENCE:}

auth0.allowed-emails=${AUTH0_ALLOWED_EMAILS:careers@fidenz.com,buddhinikaluwila1999@gmail.com}
auth0.require-mfa=${AUTH0_REQUIRE_MFA:true}